name: Bug Report
description: Report a bug in podcast-intel
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run `podcast-intel ...`
        2. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Output of `pip show podcast-intel`
      placeholder: "0.1.0"
    validations:
      required: true
  - type: input
    id: python
    attributes:
      label: Python version
      description: Output of `python --version`
      placeholder: "3.12.0"
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other context, logs, or screenshots.
