name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem or motivation
      description: What problem does this feature solve? Why is it needed?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the solution you'd like.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or workarounds you've considered.
  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of podcast-intel does this relate to?
      options:
        - PQS Scoring
        - Transcription
        - Analysis (NER, sentiment, fillers)
        - CLI
        - Reports
        - Database / Models
        - Documentation
        - Other
    validations:
      required: true
